export const testProfiles = [
    { region: "US", fromCurrency: "USD", toCurrency: "ALL", amount: "100" },
  { region: "India", fromCurrency: "INR", toCurrency: "USD", amount: "5000" },
  { region: "Japan", fromCurrency: "JPY", toCurrency: "GBP", amount: "10000" },
  { region: "US", fromCurrency: "USD", toCurrency: "ALL", amount: "100" },
  { region: "India", fromCurrency: "INR", toCurrency: "USD", amount: "5000" },
  { region: "Japan", fromCurrency: "JPY", toCurrency: "GBP", amount: "10000" },
  { region: "UK", fromCurrency: "GBP", toCurrency: "EUR", amount: "300" },
  { region: "Germany", fromCurrency: "EUR", toCurrency: "CHF", amount: "250" },
  // { region: "Canada", fromCurrency: "CAD", toCurrency: "USD", amount: "400" },
  // { region: "Australia", fromCurrency: "AUD", toCurrency: "NZD", amount: "350" },
  // { region: "China", fromCurrency: "CNY", toCurrency: "USD", amount: "5000" },
  // { region: "Brazil", fromCurrency: "BRL", toCurrency: "EUR", amount: "1500" },
  // { region: "South Korea", fromCurrency: "KRW", toCurrency: "JPY", amount: "200000" },
  // { region: "Russia", fromCurrency: "RUB", toCurrency: "USD", amount: "30000" },
  // { region: "Mexico", fromCurrency: "MXN", toCurrency: "CAD", amount: "6000" },
  // { region: "Nigeria", fromCurrency: "NGN", toCurrency: "USD", amount: "80000" },
  // { region: "South Africa", fromCurrency: "ZAR", toCurrency: "GBP", amount: "7000" },
  // { region: "UAE", fromCurrency: "AED", toCurrency: "INR", amount: "1200" },
  // { region: "Singapore", fromCurrency: "SGD", toCurrency: "USD", amount: "900" },
  // { region: "Switzerland", fromCurrency: "CHF", toCurrency: "EUR", amount: "1000" },
  // { region: "Sweden", fromCurrency: "SEK", toCurrency: "NOK", amount: "2000" },
  // { region: "Norway", fromCurrency: "NOK", toCurrency: "DKK", amount: "1700" },
  // { region: "Denmark", fromCurrency: "DKK", toCurrency: "EUR", amount: "2200" },
  // { region: "Pakistan", fromCurrency: "PKR", toCurrency: "USD", amount: "150000" },
  // { region: "Bangladesh", fromCurrency: "BDT", toCurrency: "INR", amount: "100000" },
  // { region: "Vietnam", fromCurrency: "VND", toCurrency: "USD", amount: "2000000" },
  // { region: "Thailand", fromCurrency: "THB", toCurrency: "CNY", amount: "50000" },
  // { region: "Philippines", fromCurrency: "PHP", toCurrency: "JPY", amount: "60000" },
  // { region: "Indonesia", fromCurrency: "IDR", toCurrency: "USD", amount: "3000000" },
  // { region: "Malaysia", fromCurrency: "MYR", toCurrency: "SGD", amount: "1800" },
  // { region: "Sri Lanka", fromCurrency: "LKR", toCurrency: "INR", amount: "120000" },
  // { region: "Argentina", fromCurrency: "ARS", toCurrency: "USD", amount: "25000" },
  // { region: "Turkey", fromCurrency: "TRY", toCurrency: "EUR", amount: "13000" },
  // { region: "Poland", fromCurrency: "PLN", toCurrency: "USD", amount: "1100" },
  // { region: "Czech Republic", fromCurrency: "CZK", toCurrency: "EUR", amount: "3000" },
  // { region: "Hungary", fromCurrency: "HUF", toCurrency: "GBP", amount: "500000" },
  // { region: "Egypt", fromCurrency: "EGP", toCurrency: "USD", amount: "4000" },
  // { region: "Israel", fromCurrency: "ILS", toCurrency: "EUR", amount: "2000" },
  // { region: "New Zealand", fromCurrency: "NZD", toCurrency: "AUD", amount: "600" },
  // { region: "Chile", fromCurrency: "CLP", toCurrency: "USD", amount: "150000" },
  // { region: "Colombia", fromCurrency: "COP", toCurrency: "USD", amount: "1000000" },
  // { region: "Ukraine", fromCurrency: "UAH", toCurrency: "EUR", amount: "50000" },
  // { region: "Kazakhstan", fromCurrency: "KZT", toCurrency: "USD", amount: "200000" },
  // { region: "Kenya", fromCurrency: "KES", toCurrency: "EUR", amount: "100000" },
  // { region: "Ghana", fromCurrency: "GHS", toCurrency: "USD", amount: "9000" },
  // { region: "Morocco", fromCurrency: "MAD", toCurrency: "EUR", amount: "3500" },
  // { region: "Romania", fromCurrency: "RON", toCurrency: "USD", amount: "2500" },
  // { region: "Serbia", fromCurrency: "RSD", toCurrency: "EUR", amount: "10000" },
  // { region: "Croatia", fromCurrency: "EUR", toCurrency: "HRK", amount: "100" },
  // { region: "Iceland", fromCurrency: "ISK", toCurrency: "USD", amount: "50000" },
  // { region: "Hong Kong", fromCurrency: "HKD", toCurrency: "CNY", amount: "3000" },
  // { region: "Taiwan", fromCurrency: "TWD", toCurrency: "JPY", amount: "40000" },
];
 