name: Run Playwright Tests

on:
  repository_dispatch:
    types: [jira_trigger]

jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Print issue key
        env:
          ISSUE_KEY: ${{ github.event.client_payload.issue_key }}
        run: echo "$ISSUE_KEY"

      - name: Fail if issue key is missing
        env:
          ISSUE_KEY: ${{ github.event.client_payload.issue_key }}
        run: |
          if [ -z "$ISSUE_KEY" ]; then
            echo "ISSUE_KEY is missing!"
            exit 1
          fi

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install dependencies
        run: npm install
          
      - name: Fix permissions
        run: chmod +x node_modules/.bin/playwright
          
      - name: Run Playwright tests
        run: npm run runtest
          
      - name: Send results to JIRA
        env:
          JIRA_URL: "https://saurabhgunturkar07.atlassian.net/"
          JIRA_USER: "saurabhgunturkar07@gmail.com"
          JIRA_API_TOKEN: "${{ secrets.JIRA_API_TOKEN }}"
          ISSUE_KEY: ${{ github.event.client_payload.issue_key }}
        run: node send-results-to-jira.js
